In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_excel('Jobdemandbyindustry.xlsx')

In [3]:
df

,Unnamed: 0,"Australia ; Agriculture, Forestry and Fishing ; Employed total ;","Australia ; Agriculture, Forestry and Fishing ; > Employed full-time ;","Australia ; Agriculture, Forestry and Fishing ; > Employed part-time ;",Australia ; Mining ; Employed total ;,Australia ; Mining ; > Employed full-time ;,Australia ; Mining ; > Employed part-time ;,Australia ; Manufacturing ; Employed total ;,Australia ; Manufacturing ; > Employed full-time ;,Australia ; Manufacturing ; > Employed part-time ;,...,"> South Australia ; Agriculture, Forestry and Fishing ; Employed total ;","> South Australia ; Agriculture, Forestry and Fishing ; > Employed full-time ;","> South Australia ; Agriculture, Forestry and Fishing ; > Employed part-time ;",> South Australia ; Mining ; Employed total ;,> South Australia ; Mining ; > Employed full-time ;,> South Australia ; Mining ; > Employed part-time ;,> South Australia ; Manufacturing ; Employed total ;,> South Australia ; Manufacturing ; > Employed full-time ;,> South Australia ; Manufacturing ; > Employed part-time ;,"> South Australia ; Electricity, Gas, Water and Waste Services ; Employed total ;"
0,1984-11-01,410.719753,338.746656,71.973098,94.057826,91.346108,2.711717,1098.832280,1018.184144,80.648135,...,41.788429,33.312444,8.475985,6.019670,5.921096,0.098573,108.785886,100.794776,7.991110,10.770859
1,1985-02-01,404.842338,327.217337,77.625001,95.211764,92.779602,2.432162,1095.389725,1016.561028,78.828697,...,43.133586,34.072660,9.060925,6.287407,6.066471,0.220936,105.740147,98.944671,6.795476,11.046959
2,1985-05-01,394.461506,319.238199,75.223307,92.927913,90.560783,2.367130,1080.521491,1001.839997,78.681494,...,46.616807,36.899441,9.717366,8.464117,8.009378,0.454739,101.524334,95.056029,6.468305,11.379726
3,1985-08-01,413.675791,334.235215,79.440576,101.612776,100.018753,1.594023,1057.185845,972.724663,84.461181,...,44.644989,36.017178,8.627811,8.236106,7.785615,0.450491,97.030741,89.788545,7.242196,10.193841
4,1985-11-01,433.581180,349.292384,84.288796,108.770890,106.572470,2.198420,1085.807292,1003.302966,82.504326,...,47.535986,38.504849,9.031137,9.340956,9.340956,0.000000,105.385405,97.504953,7.880452,10.715301
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137,2019-02-01,346.213207,245.553171,100.660036,245.365866,235.526273,9.839594,856.734745,732.579244,124.155500,...,37.121187,28.345075,8.776112,13.349407,12.591704,0.757703,75.207496,64.626059,10.581437,11.341589
138,2019-05-01,334.411332,241.581248,92.830083,240.231414,231.619059,8.612355,910.146835,770.793207,139.353628,...,31.857109,23.725419,8.131690,7.744621,7.525149,0.219472,71.596146,59.131938,12.464208,13.036051
139,2019-08-01,319.032738,239.440679,79.592058,234.977027,227.525856,7.451171,855.000593,705.993307,149.007286,...,31.520330,25.283407,6.236923,10.092376,10.092376,0.000000,63.206648,50.459124,12.747524,13.749662
140,2019-11-01,318.964108,238.700565,80.263542,251.255041,238.359322,12.895719,916.502293,776.975638,139.526655,...,30.125432,21.329438,8.795994,13.753925,13.529824,0.224101,70.999538,57.512403,13.487135,11.455775
141,2020-02-01,337.223927,250.903509,86.320418,238.367264,228.300101,10.067163,909.796864,774.284734,135.512131,...,28.700820,18.559104,10.141716,11.221715,10.521255,0.700460,78.063184,64.083457,13.979727,12.766268

In [4]:
df = df[df.columns[~df.columns.str.endswith('Employed full-time ;')]]

In [5]:
df = df[df.columns[~df.columns.str.endswith('Employed part-time ;')]]

In [19]:
df.columns = df.columns.str.replace('Australia ;', '')

In [23]:
df.columns = df.columns.str.replace('>', '')

In [26]:
df.columns = df.columns.str.lstrip()

In [29]:
z=df.loc[:, 'New South Wales ;  Agriculture, Forestry and Fishing':]

In [37]:
df.drop(df.loc[:,'New South Wales ;  Agriculture, Forestry and Fishing':], axis=1,inplace=True)

In [40]:
df.to_excel('jobbysalarycleaned.xlsx', 'w')