In [1]:
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
import plotly.figure_factory as ff
from plotly.subplots import make_subplots
import plotly as py

In [4]:
df=pd.read_csv(r'indeedcoJD.csv')

In [3]:
import requests
import bs4
from bs4 import BeautifulSoup
from selenium import webdriver
from urllib.request import urlopen
import pandas as pd
import numpy as np

In [5]:
df.isnull().sum()

Unnamed: 0              0
Jobtitle                0
Company                25
City                  858
State                 498
FormattedLocation       0
Date                    0
Snippet                 0
URL                     0
Latitude              858
Longitude             858
Salary               3805
Rating               3805
full_jd              4451
dtype: int64

In [6]:
df1=pd.read_csv(r'resume_samples_10000.csv')

In [7]:
df3=pd.read_excel(r'salarybyindustry.xlsx')

In [8]:
df3

,Date,Accommodation and Food Services,Administrative and Support Services,Arts and Recreation Services,Construction,Education and Training,"Electricity, Gas, Water and Waste Services",Financial and Insurance Services,Health Care and Social Assistance,Information Media and Telecommunications,Manufacturing,Mining,Other Services,"Professional, Scientific and Technical Services",Public Administration and Safety,"Rental, Hiring and Real Estate Services",Retail Trade,Total All Industries,"Transport, Postal and Warehousing",Wholesale Trade
0,2010-05-01,967.1,1817.1,1339.6,2149.2,2080.7,2860.6,2706.3,2268.8,2680.6,2027.2,3702.2,1682.9,2610.5,2474.8,2063.1,1271.6,2026.6,2137.5,2036.0
1,2010-11-01,1019.2,1848.6,1433.6,2107.4,2128.9,2966.8,2839.8,2310.2,2749.4,2038.4,3839.1,1760.8,2696.3,2552.5,2137.4,1267.6,2073.7,2239.0,2117.3
2,2011-05-01,979.0,1758.3,1485.3,2267.7,2153.3,3047.1,2819.8,2334.4,2746.5,2102.9,3869.6,1707.8,2733.8,2578.0,2095.3,1229.5,2112.3,2250.8,2269.9
3,2011-11-01,1014.5,1715.0,1430.8,2250.7,2178.4,3084.3,2917.3,2381.6,2724.5,2112.3,4005.1,1738.1,2761.4,2623.9,2046.4,1280.0,2140.4,2311.3,2411.8
4,2012-05-01,1025.1,1822.3,1469.5,2326.8,2259.2,3070.9,2907.3,2324.3,2816.9,2054.5,4188.1,1776.3,2782.4,2681.8,2085.5,1294.9,2187.9,2418.6,2483.3
5,2012-11-01,1076.5,1838.6,1515.4,2375.4,2320.8,3216.3,2979.8,2349.8,2866.5,2135.7,4398.5,1830.5,2830.5,2745.6,2200.2,1326.3,2234.6,2463.6,2479.7
6,2013-05-01,1099.3,1883.7,1648.7,2489.0,2349.5,3248.9,2980.6,2455.7,2950.2,2239.4,4512.5,1890.4,2885.0,2762.1,2092.9,1356.4,2277.4,2490.2,2412.3
7,2013-11-01,1061.2,1875.2,1585.2,2514.2,2369.2,3229.5,3001.5,2527.0,2911.4,2294.1,4616.9,1880.5,2932.1,2823.4,2054.3,1374.1,2294.7,2554.1,2363.9
8,2014-05-01,1059.6,2020.3,1570.7,2549.8,2431.5,3305.7,3055.4,2546.5,2885.1,2247.7,4612.1,1794.1,3017.5,2809.0,2202.6,1353.4,2323.4,2558.8,2417.8
9,2014-11-01,1040.3,1881.5,1466.8,2612.2,2456.4,3301.4,3101.6,2555.5,2876.2,2340.2,4669.7,1835.0,3149.3,2796.5,2223.7,1386.0,2338.8,2538.9,2397.7
10,2015-05-01,1124.3,1910.9,1490.2,2554.5,2490.3,3320.8,3179.8,2550.1,2938.9,2354.7,4774.1,1833.0,3073.3,2828.6,2222.2,1391.8,2361.5,2586.4,2363.8
11,2015-11-01,1140.5,1919.8,1457.4,2524.3,2493.2,3399.4,3381.2,2516.6,2967.9,2371.4,4785.1,1909.1,3086.4,2874.1,2265.5,1445.6,2375.9,2557.8,2438.8
12,2016-05-01,1096.4,2003.8,1509.5,2498.3,2527.6,3402.0,3397.6,2480.4,3110.4,2396.0,4900.8,1918.7,3087.3,2879.7,2257.4,1430.4,2403.2,2607.3,2514.9
13,2016-11-01,1066.4,1945.1,1639.3,2495.2,2553.4,3551.3,3488.8,2580.6,3200.5,2457.5,4838.8,1907.5,3092.6,2947.8,2289.8,1415.7,2409.5,2588.7,2540.3
14,2017-05-01,1140.1,2078.2,1664.7,2509.3,2594.5,3549.5,3326.1,2680.8,3250.7,2377.3,4817.1,2013.1,3079.9,2959.3,2404.5,1408.5,2443.5,2683.7,2650.9
15,2017-11-01,1141.0,2053.8,1709.0,2609.9,2543.2,3592.3,3316.3,2624.0,3304.4,2480.6,4824.1,2012.9,3134.6,3045.0,2450.0,1471.5,2458.5,2727.2,2588.7
16,2018-05-01,1097.0,2159.8,1838.8,2642.7,2582.8,3601.4,3340.6,2685.0,3251.8,2497.6,4847.4,1946.8,3126.1,3072.1,2451.3,1505.9,2493.6,2853.9,2633.0
17,2018-11-01,1115.3,2170.2,1863.2,2545.6,2594.4,3633.0,3469.5,2721.8,3373.3,2565.5,4947.3,1994.7,3232.0,3124.9,2354.4,1547.5,2529.2,2794.9,2697.6
18,2019-05-01,1123.1,2246.3,1828.1,2662.0,2668.1,3724.6,3576.8,2767.7,3358.6,2550.2,4984.5,1947.8,3279.5,3128.9,2338.9,1560.9,2561.6,2890.3,2706.2
19,2019-11-01,1174.9,2133.7,1770.6,2784.5,2710.4,3704.4,3547.4,2798.1,3309.8,2551.4,5003.6,1955.9,3298.0,3248.3,2443.3,1651.5,2602.6,2997.2,2691.0
20,2020-05-01,1203.2,2242.5,2033.2,2905.1,2823.6,3774.5,3607.6,2812.8,3497.5,2624.2,5154.8,2086.4,3405.5,3293.2,2400.9,1624.7,2697.9,2845.9,2748.0